### PR TITLE
fix: don't write empty license files

### PR DESCRIPTION
**Pull request by filipesilva**
Related to #13

### CODE REVIEW

**Comment by xz64** [comment]
@filipesilva  Thanks. By the way, I am going to add an option to produce a "master" license file which is aggregated from every chunk. It should be ready within next couple days. I'll let you know when

**Comment by filipesilva** [comment]
Oh thanks, that's nice to hear! For now I added a temporary PR to Angular CLI to prepare for chunk based licenses anyway. When I thought more about it, I think it makes a lot of sense as well.

**Comment by xz64** [comment]
@filipesilva  v1 is published now

**Comment by filipesilva** [comment]
Thank you for letting me know, and for implementing these changes. I'll update Angular CLI to use it with the new options.

**Pull request merged**
